version: '3.7'

services:

  santafe-mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: santa
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: santafe
    ports:
      - 27072:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
