logging.level:
  root: ${SANTAFE_LOGGING_LEVEL:info}
telegram:
  bot:
    name: ${SANTAFE_BOT_NAME}
    token: ${SANTAFE_BOT_TOKEN}
spring:
  data:
    mongodb:
      host: ${SANTAFE_MONGO_HOST:localhost}
      port: ${SANTAFE_MONGO_PORT:27072}
      username: ${SANTAFE_MONGO_USER:santa}
      password: ${SANTAFE_MONGO_PASSWORD:root}
      database: ${SANTAFE_MONGO_DBNAME:santafe}
  main:
    allow-circular-references: true
    web-application-type: none