logging.level:
  root: ${SANTAFE_LOGGING_LEVEL:info}
telegram:
  bot:
    name: ${SANTAFE_BOT_NAME}
    token: ${SANTAFE_BOT_TOKEN}
spring:
  data:
    mongodb:
      host: ${SANTAFE_MONGO_HOST}
      port: ${SANTAFE_MONGO_PORT}
      username: ${SANTAFE_MONGO_USER}
      password: ${SANTAFE_MONGO_PASSWORD}
      database: ${SANTAFE_MONGO_DBNAME}
  main:
    allow-circular-references: true
    web-application-type: none